source 'http://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'pry'
gem 'bcrypt'
gem 'koala'
gem 'dotenv'
gem 'json'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'rack-flash3'
